import { Header } from "@/components/header/Header";
import { AddTodo } from "@/components/todos/AddTodo";
import { Todo } from "@/components/todos/Todo";
import Head from "next/head";
import style from "./index.module.css";

const todosData = [
  {
    id: 1,
    name: "First Task",
  },
  {
    id: 2,
    name: "second Task",
  },
  {
    id: 3,
    name: "third Task",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={`${style.container}`}>
          <Header />
          <AddTodo />
          {todosData.map((todo, index) => (
            <Todo data={todo} key={index} />
          ))}
        </div>
      </main>
    </>
  );
}
