import { Header } from "@/components/header/Header";
import { AddTodo } from "@/components/todos/AddTodo";
import { Todo } from "@/components/todos/Todo";
import Head from "next/head";
import style from "./index.module.css";

const todosData = [
  {
    id: 1,
    name: (
      <input
        className="tasks"
        id="first_task"
        type="text"
        placeholder="First task"
      />
    ),
  },
  {
    id: 2,
    name: (
      <input
        className="tasks"
        id="second_task"
        type="text"
        placeholder="Second task"
      />
    ),
  },
  {
    id: 3,
    name: (
      <input
        className="tasks"
        id="third_task"
        type="text"
        placeholder="Third task"
      />
    ),
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={`${style.container}`}>
          <Header />
          <AddTodo />
          <button>Add task</button>
        </div>
        <div className={style.line}></div>
        <div>
          {todosData.map((todo, index) => (
            <Todo data={todo} key={index} />
          ))}
        </div>
        <div></div>
      </main>
    </>
  );
}
